# Generated by Claude Code on 2026-02-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eseme', '0007_member_memb_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('vouc_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('vouc_image', models.ImageField(upload_to='vouchers/%Y/%m/')),
                ('vouc_operation_number', models.CharField(max_length=50)),
                ('vouc_status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('vouc_created_at', models.DateTimeField(auto_now_add=True)),
                ('vouc_updated_at', models.DateTimeField(auto_now=True)),
                ('vouc_comment', models.TextField(blank=True, null=True)),
                ('vouc_member', models.ForeignKey(db_column='vouc_member', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vouchers', to='eseme.member')),
                ('vouc_period', models.ForeignKey(db_column='vouc_period', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vouchers', to='eseme.period')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-vouc_created_at'],
            },
        ),
    ]
