# Generated by Claude Code on 2026-02-08
# Migration to change ImageField to BinaryField and add metadata fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eseme', '0008_voucher'),
    ]

    operations = [
        # Remover el campo ImageField
        migrations.RemoveField(
            model_name='voucher',
            name='vouc_image',
        ),
        # Agregar BinaryField para la imagen
        migrations.AddField(
            model_name='voucher',
            name='vouc_image',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        # Agregar campo para nombre de archivo
        migrations.AddField(
            model_name='voucher',
            name='vouc_image_name',
            field=models.CharField(default='voucher.jpg', max_length=255),
            preserve_default=False,
        ),
        # Agregar campo para tipo MIME
        migrations.AddField(
            model_name='voucher',
            name='vouc_image_type',
            field=models.CharField(default='image/jpeg', max_length=50),
            preserve_default=False,
        ),
    ]
