# Generated by Django 3.x on 2026-02-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eseme', '0009_alter_voucher_image_to_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cour_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cour_type',
            field=models.TextField(blank=True),
        ),
    ]